export const types = {
  FILL_TASKS: 'FILL_TASKS',
  START_FETCHING: 'START_FETCHING',
  STOP_FETCHING: 'STOP_FETCHING',
  UPDATE_TASK: 'UPDATE_TASK',
  CREATE_TASK: 'CREATE_TASK',
  DELETE_TASK: 'DELETE_TASK',
};
